### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop-2022-viewport#1]
What are some known issues with viewport units / viewport measurement?

https://github.com/web-platform-tests/interop-2022/issues/41 lists some.

https://github.com/w3c/csswg-drafts/issues/6453 also came across my radar, but I'm not sure if it's an interop issue, I don't know current browser behavior.

**Comment by bramus** [comment]
One thing that's on my radar is the inconsistency between Safari and Chrome when it comes to viewport units and the keyboard.

As I understand it from running some tests using https://urlbarsize.netlify.app/urlbarsize-allowresize.html _(forked from https://bokand.github.io/demo/urlbarsize.html to also include a textfield you can focus)_:

- Safari on iOS calculates 100vh against the layout viewport. When the keyboard gets shown/hidden, the calculated value for 100vh does not change. The keyboard does not really overlay the contents, but Safari does this thing where [it shifts the layout viewport up](https://www.bram.us/wordpress/wp-content/uploads/2021/09/visual-viewport.png)
- In Chrome on Android, 100vh is calculated against the visual viewport. When the keyboard gets shown/hidden, the calculated value for 100vh changes along with that.

Could be that (part of) this gets solved when the [Virtual Keyboard API](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/VirtualKeyboardAPI/explainer.md) lands (allowing devs to set `overlaysContent ` to `true`), but would be nice to see all browsers use the same default behavior there.

**Comment by foolip** [comment]
The thread in https://twitter.com/madebyfabian/status/1460376294332456968 is about virtual keyboard interaction, with @jensimmons and Maciej chimed in.

**Comment by bfgeek** [comment]
There is also https://github.com/w3c/csswg-drafts/issues/7194

**Comment by gsnedders** [comment]
* Relationship between initial containing block and layout viewport and visual viewport is unspecified,
 * `height: -webkit-fill-available` is widely used, but is still prefixed everywhere (v. [`stretch`](https://www.w3.org/TR/css-sizing-4/#valdef-width-stretch), got deferred to L4,  and appears practically untested in WPT,
 * CSSOM attributes like `innerHeight` still refer to the old CSS 2 definition of viewport, so it's unspecified what they do with dynamic viewports,
 * Lack of WPT infrastructure to test dynamic viewport behaviour.

**Comment by bramus** [comment]
Mentioning https://github.com/w3c/csswg-drafts/issues/7194 as related

**Comment by foolip** [comment]
https://github.com/bokand/bokand.github.io/blob/master/web_viewports_explainer.md#initial-containing-block-icb might be relevant here.

**Comment by bramus** [comment]
Closing this issue as we will be discussing items listed here in separate issues.
