### ISSUE TITLE
How do Viewport-Percentage lengths behave on browsers with no dynamic UA UI Elements?

### ISSUE THREAD

**Issue by bramus** [web-platform-tests/interop-2022-viewport#12]
Desktop browsers for example _(currently)_ have no dynamic UA UI Elements and therefore have no [Small Viewport](https://github.com/web-platform-tests/interop-2022-viewport/blob/main/explainers/viewport-units.md#the-small-viewport) or [Large Viewport](https://github.com/web-platform-tests/interop-2022-viewport/blob/main/explainers/viewport-units.md#the-large-viewport).

It is not explicitly specced what should happen in this case: do the `sv*`/`lv*`/`dv*` become inexistent, or do they all take up the same size - i.e. that of [The UA-Default Viewport](https://github.com/web-platform-tests/interop-2022-viewport/blob/main/explainers/viewport-units.md#ua-default-viewport)?

**Comment by bramus** [comment]
The obvious thing is to let them all have the same size, and explicitly mention that in the spec.

**Comment by karlcow** [comment]
> Desktop browsers for example (currently) have no dynamic UA UI Elements 

will it be always the case?

> The obvious thing is to let them all have the same size, and explicitly mention that in the spec.

Something along, *in case there are no dynamic UI Elements*, falls back to the UA default viewport. Initial values?

**Comment by gsnedders** [comment]
> It is not explicitly specced what should happen in this case: do the sv*/lv*/dv* become inexistent, or do they all take up the same size

Is this not explicitly spec'd? The small viewport and large viewport are defined in terms of "any UA interfaces", which means they're defined even if there are no UA interfaces?

**Comment by bramus** [comment]
Discussed during https://github.com/web-platform-tests/interop-2022-viewport/issues/4. We agree that all units should all match if there are no UA UI elements. An explicit mention of this (and maybe an example) in the spec would be feasible.

**Comment by bramus** [comment]
Filed https://github.com/w3c/csswg-drafts/issues/7764 at the CSS WG to follow up on this.
