### ISSUE TITLE
Can we define the size of the UA-default Viewport?

### ISSUE THREAD

**Issue by bramus** [web-platform-tests/interop-2022-viewport#13]
The spec currently leaves some wiggle room for [the UA-default Viewport](https://github.com/web-platform-tests/interop-2022-viewport/blob/main/explainers/viewport-units.md#ua-default-viewport)

> The UA-default viewport-percentage units (v*) are defined with respect to a UA-defined UA-default viewport size, which for any given document should be equivalent to the large viewport size, small viewport size, or some intermediary size.

In practice however, all browsers seem to agree that it takes over the size of [the Large Viewport](https://github.com/web-platform-tests/interop-2022-viewport/blob/main/explainers/viewport-units.md#the-large-viewport)

Maybe we should then also have it specced like that?

**Comment by karlcow** [comment]
anything which is left to UA-defined leads to webcompat issues. So probably trying to unify on one scenario would be better.

**Comment by bramus** [comment]
Discussed during https://github.com/web-platform-tests/interop-2022-viewport/issues/4. We agree to try and pursue this.

**Comment by jensimmons** [comment]
I hope the plan is to raise this issue with the CSSWG. At https://github.com/w3c/csswg-drafts/issues

This group should not be defining anything. This group should only be:
- researching the current state of implementations
- finding bugs in browsers where they don't match web standards
- discovering areas where the standards are vague
- opening issues at the CSSWG or other standards bodies, asking them to provide clarification
- encouraging anyone involved with this group to join the CSSWG or other appropriate standards bodies (if not a member already) to carry on with the needed work inside that group

Interop 2022 is _not_ a place to be writing specifications. Such work needs to be done in a place where it is covered by patent policy. 

The CSSWG is a friendly bunch. They know work is needed on viewports. They just need help / more interested parties to get involved. This work can be done there, easily. With the help and wisdom of people who've been working in this space for decades.

**Comment by rachelandrew** [comment]
Hi Jen - yes, Bramus is a member of the CSS Working group, as am I. This is just a fact-finding mission to get enough info to raise the issue.

**Comment by bramus** [comment]
Commented on https://github.com/w3c/csswg-drafts/issues/6454#issuecomment-1251015591 to flag this. Marking this issue here as closed.
