### ISSUE TITLE
Meeting 1 (2022-05-31)

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop-2022-viewport#2]
Based on https://github.com/web-platform-tests/interop-2022/issues/41 I've gone ahead and scheduled a meeting for Tuesday, May 31, at 8am PT / 11 noon ET / 4pm UK / 5pm CET. I have invited:
- @jensimmons, from Apple (ET)
- @rachelandrew, from Google (UK)
- @bramus, from Google (CET)
- @skobes, from Google (ET)
- @ststimac, from Microsoft (PT)
- @adarosecannon, from Samsung (UK)

I've made it 30 minutes, because that's unfortunately what I can personally do, but think it's better to get started than continue to struggle with scheduling.

The meeting and following discussion might be similar to https://github.com/web-platform-tests/interop-2022-editing/issues/1, basically first exploring the space to identify the concrete work needed, then switching to execution to improve specs and tests.

Agenda to be posted here.

**Comment by bramus** [comment]
Just a heads up that @ststimac [no longer works at Microsoft](https://twitter.com/seaotta/status/1525163168644800513).

**Comment by foolip** [comment]
Thanks @bramus, I didn't know that. I did notice that @karlcow has a new employer however. @karlcow are you still interested in this effort?

**Comment by karlcow** [comment]
@foolip I let @jensimmons who has been the most active and is already involved, until I figure out things on my side. Thanks.

**Comment by foolip** [comment]
@kypflug is there someone I should invite from Microsoft?

**Comment by foolip** [comment]
I promised to post an agenda, better late than never:
- Hello
- https://github.com/web-platform-tests/interop-2022-viewport/issues/1, fielding of known issues from other places based on people's experience
- Milestones for this work. Roughly: define the areas we'll endeavor to fix, give each an owner, define our progress (as a score) in terms of those areas
- Cadence and time for meeting

**Comment by jgraham** [comment]
@emilio @hiikezoe are you the right people to be involved from Mozilla, or alternatively do you know if there's someone else who ought participate in this viewport investigation work?

**Comment by foolip** [comment]
_Brief notes from the meeting_

Attending: @rachelandrew @AdaRoseCannon @bramus @skobes @foolip

Brainstormed list of issues:
- https://github.com/web-platform-tests/interop-2022/issues/4#issuecomment-962116857
- https://github.com/web-platform-tests/interop-2022/issues/41#issuecomment-1022798478
- https://github.com/web-platform-tests/interop-2022-viewport/issues/1#issuecomment-1138787450
- For mobile scrolling, when does the address bar animate away, when do events fire, when do units change their meaning?
  - What triggers the resize?
  - How does the page react to the resize?
- Testing this is hard, mobile browsers aren't tested in WPT.
- Virtual keyboard, Safari treats the keyboard as an "overlay" while Chrome shrinks the viewport. https://w3c.github.io/virtual-keyboard/
- Many issues in the CSSWG, go through all of those issues and make sure they're being addressed
- Scrollbars, whether or not 100vw unit shrinks when scrollbar is shown?
- Agree on what `vh` means, should it be `lvh`?
- Relationship between viewport(s) and initial containing block
- Samsung Internet might have some differences to Chrome on Android, because it's a different implementation. Needs investigation. [New viewport units](https://bugs.chromium.org/p/chromium/issues/detail?id=1093055) not enabled for stable in Chromium yet.

@rachelandrew volunteers to look through open CSSWG issues, make a list.

@bramus volunteers to look through differences between browsers in regular `vh` unit and Visual Viewport API.

**Comment by emilio** [comment]
@hiikezoe is probably more familiar than me with some of the tricky compat issues, also @theres-waldo perhaps.

But if they can't make it due to timezone issues or conflicts I'm happy to attend this.

**Comment by hiikezoe** [comment]
I am afraid, it's midnight in my time zone so that I won't be able to join the meeting :/ 

>     * Testing this is hard, mobile browsers aren't tested in WPT.

I don't think testing is so hard. Mozilla has been running WPTs on a gecko-based mobile browser, unfortunately the browser doesn't have dynamic toolbar yet (there is [an open bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1685242) to implement dynamic toolbar in the browser, and fixing it should be straight forward).

And if WebDriver can invoke __native__ touch events, we could have more interesting test cases.

**Comment by bramus** [comment]
Issue for the `100vw` vs scrollbars: https://github.com/w3c/csswg-drafts/issues/6026
