### ISSUE TITLE
Clarify our Mission Statement and Process

### ISSUE THREAD

**Issue by bramus** [web-platform-tests/interop-2022-viewport#21]
In this repository’s README there is short goal – or “Mission Statement” if you would like to call it that way – which was [quoted from here](https://github.com/web-platform-tests/interop/issues/41#issuecomment-1005952552):

> To sort out any confusion about what “viewport” means, and what browsers (especially on mobile devices) should be doing with various viewport measurements & sizing. To make recommendations for what should change to improve interoperability.

It has come to my attention that this is not clear, given the pushback in the following issues:

- https://github.com/web-platform-tests/interop-2022-viewport/issues/13#issuecomment-1227267880
- https://github.com/web-platform-tests/interop-2022-viewport/issues/14#issuecomment-1227271832
- https://github.com/web-platform-tests/interop-2022-viewport/issues/15#issuecomment-1227271077

To be clear: yes, the plan is to pursue clarification/resolution/… at the proper venues that have the authority to do so (e.g. CSSWG), file bugs with the relevant vendors, etc.

Note that this was mentioned during previous meetings https://github.com/web-platform-tests/interop-2022-viewport/issues/3 and https://github.com/web-platform-tests/interop-2022-viewport/issues/4, but not reflected in the notes. Apologies for failing to properly write up meeting notes, making this unclear to external people / people who were not able to attend.

As also mentioned during the previous meetings I am very open to feedback on the current process, and would like to discuss this first during the next meeting.

/cc @jensimmons @karlcow @fantasai

**Comment by karlcow** [comment]
There are two sentences in the scope of the work which I think represent the intent of what @jensimmons had written in the passage you quoted which is in the goal. 

> Open any issues at CSSWG, WHATWG, wherever if we find underspecified standards on what these measurements should be in relationship to the viewport — so that the appropriate standards group can take it from there & define any missing details.
> Open any issues/bugs with the appropriate browsers, noting places where they are not aligned with the standard. Or if the standard is unclear, where they are not aligned with each other.

**Comment by foolip** [comment]
I think it would be great to put some of that language into the README to document how we will work.

The linked issues would make sense to file as spec issues, and I don't think there's any disagreement about that, just a question of when it happens. Soonish, I presume.

**Comment by bramus** [comment]
Discussed during https://github.com/web-platform-tests/interop-2022-viewport/issues/20. We will include the extra wording to make our intentions clear.
