### ISSUE TITLE
Update progress score 

### ISSUE THREAD

**Issue by bramus** [web-platform-tests/interop-2022-viewport#22]
Quoting https://github.com/web-platform-tests/interop-2022-viewport/issues/20#issuecomment-1226262946

> A decision on how progress on the overall investigation effort will be scored, and that the viewport team makes a first recommendation on what the current score should be?

**Comment by bramus** [comment]
Discussed during https://github.com/web-platform-tests/interop-2022-viewport/issues/20. Lacking a proper framework, it feels like picking an abitrary number.

We do see two parts:
1. Identifying the issues
2. Pursuing fixes for the issues

We think we are over 50%, but lacking a proper framework we don’t know which exact score to give us yet.

**Comment by foolip** [comment]
@bramus this is going to be somewhat subjective, no doubt about it. Are you done with the first step and what remains is pursuing fixes? If so, and if you think the first part represents about half of the work, then calling it 50% and scoring the rest based on the number of issues resolved sounds fine. How many distinct issues are you splitting this into?

**Comment by bramus** [comment]
Sounds good. Would say we’re at 60% in that case.

**Comment by foolip** [comment]
Thanks @bramus! I'll bring this up in the interop meeting today, and work on the code to integrate the score of investigation efforts into the total score.

**Comment by jensimmons** [comment]
In mid-September you judged this effort to be 60% complete. It's now two months later. Is 60% still the correct number? Could you update your score?

**Comment by bramus** [comment]
We discussed this during #28.

Overall we think we’ve discussed all problem areas that we have identified, except for one: `-webkit-fill-available` (#18). This is still a bit of a dark area that has not been properly discussed. Events also weren’t discussed in this effort.

As a result, we think we can end up with a rather high score of 85% to 90%.

This score is under the assumption that the remainder of the current open https://github.com/web-platform-tests/interop-2022-viewport/labels/Discussed issues get closed by doing the follow-up work at the proper venues. @bramus will do so this week.

**Comment by foolip** [comment]
Thanks for the update @bramus! Do you think that 60% is accurate as of today, or when should we update the score to 85%, 90% or something between 60% and those?

**Comment by bramus** [comment]
The proposed score of 85%-90% is accurate as of last week.

**Comment by foolip** [comment]
@bramus shall we call it 90% then? I have to pick a specific number :)

**Comment by foolip** [comment]
I've sent https://github.com/web-platform-tests/wpt.fyi/pull/3084 to call it 90%. We'll need sign-off from the interop team before we merge that, I'll put it on the agenda for the next meeting (Thursday).

**Comment by foolip** [comment]
If I got the math right, that should give exactly a 1% bump in everyone's scores.

**Comment by bramus** [comment]
Perfect!
