### ISSUE TITLE
Clarify on the license

### ISSUE THREAD

**Issue by bramus** [web-platform-tests/interop-2022-viewport#5]
For clarity we should add a license to this repository. 

Looking at https://github.com/WICG/input-for-workers/ for inspiration, I came up with this license statement:

> All Documents in this Repository are licensed by Contributors under the [W3C Software and Document License](http://www.w3.org/Consortium/Legal/2015/copyright-software-and-document).
> 
> Code Contributions are made under the [W3C 3-clause BSD License](https://www.w3.org/Consortium/Legal/2008/03-bsd-license.html)

I could not immediately find licences regarding documents in the WPT repositories, but the [W3C Software and Document License](http://www.w3.org/Consortium/Legal/2015/copyright-software-and-document) aligns with [the license the CSS WG uses](https://github.com/w3c/csswg-drafts/blob/main/LICENSE.md).

The mentioned  [W3C 3-clause BSD License](https://www.w3.org/Consortium/Legal/2008/03-bsd-license.html) for code contributions aligns with [the license for the web platform tests themselves](https://github.com/web-platform-tests/wpt/blob/master/LICENSE.md).

Contributions to external organisations/venues fall under their set license guidelines.

Does this seem reasonable? Or do we need a different type of license?

**Comment by foolip** [comment]
Let's use the license in https://github.com/web-platform-tests/wpt/blob/master/LICENSE.md, that makes it easier to copy test material between the repos.

**Comment by foolip** [comment]
Fixed in https://github.com/web-platform-tests/interop-2022-viewport/commit/9ed4f6f29053f79da04f1cb217c76575c6a3ab97.

**Comment by bramus** [comment]
The [W3C 3-clause BSD License](https://www.w3.org/Consortium/Legal/2008/03-bsd-license.html) seems logical for the code contained in the repo, but not for documents.

For documents I suggested the [W3C Software and Document License](http://www.w3.org/Consortium/Legal/2015/copyright-software-and-document). If that would too limiting, maybe a [CC-BY license](https://creativecommons.org/licenses/by/4.0/) would do?

**Comment by foolip** [comment]
@bramus we have documentation in WPT under https://github.com/web-platform-tests/wpt/tree/master/docs and for simplicity I'd suggest doing the same. But if you intent to use something existing under another license, or to eventually send patches to some other repo with another license, then feel free to use whatever license makes that possible.
